# H2 Database Configuration
spring:
  datasource:
    url: jdbc:h2:./testdb;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password: password

  # Hibernate Configuration
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      org:
        hibernate:
          envers:
            store_data_at_delete: true
      hibernate:
        envers:
          autoRegisterListeners: true
        format_sql: true
    open-in-view: false

  # Hibernate H2 Console
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    web: DEBUG